authors:
  vuongdat67:
    name: Vuong Thanh Dat
    description: "Dat is a cyber security with a passion for building scalable web applications."
    avatar: assets/images/coding1.webp
    url: https://github.com/vuongdat67

